#include "labels.h"

const char *const labels_ru[LABEL_END] = {
    [LABEL_SUNDAY]          = "Воскресенье",
    [LABEL_MONDAY]          = "Понедельник",
    [LABEL_TUESDAY]         = "Вторник",
    [LABEL_WEDNESDAY]       = "Среда",
    [LABEL_THURSDAY]        = "Четверг",
    [LABEL_FRIDAY]          = "Пятница",
    [LABEL_SATURDAY]        = "Cуббота",

    [LABEL_JANUARY]         = "января",
    [LABEL_FEBRUARY]        = "февраля",
    [LABEL_MARCH]           = "марта",
    [LABEL_APRIL]           = "апреля",
    [LABEL_MAY]             = "мая",
    [LABEL_JUNE]            = "июня",
    [LABEL_JULY]            = "июля",
    [LABEL_AUGUST]          = "августа",
    [LABEL_SEPTEMBER]       = "сентября",
    [LABEL_OCTOBER]         = "октября",
    [LABEL_NOVEMBER]        = "ноября",
    [LABEL_DECEMBER]        = "декабря",

    [LABEL_VOLUME]          = "Громкость",
    [LABEL_BASS]            = "Тембр НЧ",
    [LABEL_MIDDLE]          = "Тембр СЧ",
    [LABEL_TREBLE]          = "Тембр ВЧ",
    [LABEL_FRONTREAR]       = "Фронт/тыл",
    [LABEL_BALANCE]         = "Баланс",
    [LABEL_CENTER]          = "Центр",
    [LABEL_SUBWOOFER]       = "Сабвуфер",
    [LABEL_PREAMP]          = "Усиление",

    [LABEL_IN_TUNER]        = "Тюнер",
    [LABEL_IN_PC]           = "Компьютер",
    [LABEL_IN_TV]           = "Телевизор",
    [LABEL_IN_BLUETOOTH]    = "Bluetooth",
    [LABEL_IN_DVD]          = "DVD",
    [LABEL_IN_USB]          = "USB",
    [LABEL_IN_MICROPHONE]   = "Микрофон",
    [LABEL_IN_GUITAR]       = "Гитара",
    [LABEL_IN_TURNTABLES]   = "Вертушки",
    [LABEL_IN_SDCARD]       = "SD карта",
    [LABEL_IN_PROJECTOR]    = "Проектор",
    [LABEL_IN_SATELLITE]    = "Спутник",
    [LABEL_IN_MIXER]        = "Микшер",
    [LABEL_IN_KARADIO]      = "KaRadio",

    [LABEL_BOOL_OFF]        = "ВЫКЛ",
    [LABEL_BOOL_ON]         = "ВКЛ",

    [LABEL_SETUP_MAIN]      = "Настройки",
    [LABEL_SETUP_TIME]      = "Время",
    [LABEL_SETUP_DATE]      = "Дата",
    [LABEL_SETUP_ALARM]     = "Будильник",
    [LABEL_SETUP_REMOTE]    = "Пульт ДУ",

    [LABEL_ALARM_DAY_OFF]       = "отключен",
    [LABEL_ALARM_DAY_WEEKDAYS]  = "будни",
    [LABEL_ALARM_DAY_ALL_DAYS]  = "все дни",
};
