#include "labels.h"

const char *const labels_en[LABEL_END] = {
    [LABEL_SUNDAY]          = "Sunday",
    [LABEL_MONDAY]          = "Monday",
    [LABEL_TUESDAY]         = "Tuesday",
    [LABEL_WEDNESDAY]       = "Wednesday",
    [LABEL_THURSDAY]        = "Thursday",
    [LABEL_FRIDAY]          = "Friday",
    [LABEL_SATURDAY]        = "Saturday",

    [LABEL_JANUARY]         = "January",
    [LABEL_FEBRUARY]        = "February",
    [LABEL_MARCH]           = "March",
    [LABEL_APRIL]           = "April",
    [LABEL_MAY]             = "May",
    [LABEL_JUNE]            = "June",
    [LABEL_JULY]            = "July",
    [LABEL_AUGUST]          = "August",
    [LABEL_SEPTEMBER]       = "September",
    [LABEL_OCTOBER]         = "October",
    [LABEL_NOVEMBER]        = "November",
    [LABEL_DECEMBER]        = "December",

    [LABEL_VOLUME]          = "Volume",
    [LABEL_BASS]            = "Bass",
    [LABEL_MIDDLE]          = "Middle",
    [LABEL_TREBLE]          = "Treble",
    [LABEL_FRONTREAR]       = "Front/rear",
    [LABEL_BALANCE]         = "Balance",
    [LABEL_CENTER]          = "Center",
    [LABEL_SUBWOOFER]       = "Subwoofer",
    [LABEL_PREAMP]          = "Preamp",

    [LABEL_IN_TUNER]        = "Tuner",
    [LABEL_IN_PC]           = "Computer",
    [LABEL_IN_TV]           = "TV set",
    [LABEL_IN_BLUETOOTH]    = "Bluetooth",
    [LABEL_IN_DVD]          = "DVD",
    [LABEL_IN_USB]          = "USB",
    [LABEL_IN_MICROPHONE]   = "Microphone",
    [LABEL_IN_GUITAR]       = "Guitar",
    [LABEL_IN_TURNTABLES]   = "Turntables",
    [LABEL_IN_SDCARD]       = "SD card",
    [LABEL_IN_PROJECTOR]    = "Projector",
    [LABEL_IN_SATELLITE]    = "Satellite",
    [LABEL_IN_MIXER]        = "Mixer",
    [LABEL_IN_KARADIO]      = "KaRadio",

    [LABEL_BOOL_OFF]        = "OFF",
    [LABEL_BOOL_ON]         = "ON",

    [LABEL_SETUP_MAIN]      = "Setup",
    [LABEL_SETUP_TIME]      = "Time",
    [LABEL_SETUP_ALARM]     = "Alarm",
    [LABEL_SETUP_REMOTE]    = "Remote",
};
